/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dancing_iron_man.glb 
Author: maskedboy123 (https://sketchfab.com/maskedboy123)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dancing-iron-man-723d889fc36544a4849da321442152fb
Title: Dancing Iron Man
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function DModelTwo(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/dancing_iron_man.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  React.useEffect(() => {
    if (actions) {
      // You'll need to console.log the actions first to find the correct animation name
      console.log("Available animations:", Object.keys(actions));

      // Once you know the correct animation name, replace 'danceName'
      actions["Swing Dancing"]?.play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={4.085}
        >
          <group
            name="fbx_mergefbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="g_spine01_offset"
                  position={[2.874, 48.184, -1.103]}
                  rotation={[-1.581, 0, Math.PI / 2]}
                >
                  <group name="Object_10">
                    <primitive object={nodes._rootJoint} />
                    <group
                      name="Object_98"
                      position={[0, 0.56, -0.665]}
                      rotation={[-1.581, 0, 0]}
                    />
                    <skinnedMesh
                      name="Object_99"
                      geometry={nodes.Object_99.geometry}
                      material={materials["IronMan.001"]}
                      skeleton={nodes.Object_99.skeleton}
                    />
                  </group>
                </group>
                <group
                  name="Light"
                  position={[407.625, 590.386, -100.545]}
                  rotation={[1.89, 0.881, -2.045]}
                  scale={100}
                >
                  <group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_6" />
                  </group>
                </group>
                <group
                  name="Camera"
                  position={[735.889, 495.831, 692.579]}
                  rotation={[Math.PI, 0.756, 2.68]}
                  scale={100}
                >
                  <group name="Object_8" />
                </group>
                <group
                  name="mesh0"
                  position={[0, 0.56, -0.665]}
                  rotation={[-1.581, 0, 0]}
                />
                <group
                  name="Sun"
                  position={[41.947, 57.401, 0]}
                  rotation={[0.034, -0.032, -1.517]}
                  scale={100}
                >
                  <group name="Object_102" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_103" />
                  </group>
                </group>
                <group
                  name="Sun001"
                  position={[32.012, 131.359, 0]}
                  rotation={[0.081, -0.097, -1.522]}
                  scale={100}
                >
                  <group name="Object_105" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_106" />
                  </group>
                </group>
                <group
                  name="Sun002"
                  position={[-3.864, 139.638, 0]}
                  rotation={[0.072, -0.099, -1.93]}
                  scale={100}
                >
                  <group name="Object_108" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_109" />
                  </group>
                </group>
                <group
                  name="Sun003"
                  position={[-46.362, 119.217, 0]}
                  rotation={[-0.13, -0.09, -1.185]}
                  scale={100}
                >
                  <group name="Object_111" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_112" />
                  </group>
                </group>
                <group
                  name="Sun004"
                  position={[-56.297, 46.362, 0]}
                  rotation={[1.014, 0.115, -1.478]}
                  scale={100}
                >
                  <group name="Object_114" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_115" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/dancing_iron_man.glb");
