/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 desk.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function DeskModel(props) {
  const { nodes, materials } = useGLTF('/desk.glb')
  return (
    <group {...props} dispose={null} position={props.position} scale={props.scale}>
      <group scale={0.01}>
        <group position={[-4.243, -1.111, 1324.662]} rotation={[-Math.PI / 2, 0, 0]} scale={1216.632}>
          <mesh geometry={nodes.SPOT005_Standard_2014_0.geometry} material={materials['Standard_2.014']} position={[0, 0, 0.009]} rotation={[-Math.PI, 0, 0]} />
        </group>
        <group position={[0.256, 47.267, 93.538]} rotation={[-1.465, -0.002, 3.123]} scale={349.633}>
          <mesh geometry={nodes.ironhead_low_head_0.geometry} material={materials.head} />
          <mesh geometry={nodes.ironheadeye_eyeand_other_0.geometry} material={materials.eyeand_other} />
        </group>
        <group position={[0, 1.084, 0]} rotation={[Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['SPOT001_Material_#39014_0'].geometry} material={materials['Material_39.014']} />
          <mesh geometry={nodes['SPOT001_Material_#40015_0'].geometry} material={materials['Material_40.015']} />
          <mesh geometry={nodes.SPOT001_Standard_2014_0.geometry} material={materials['Standard_2.014']} />
        </group>
        <group position={[734.824, 1.084, 0]} rotation={[Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['SPOT003_Material_#39014_0'].geometry} material={materials['Material_39.014']} />
          <mesh geometry={nodes['SPOT003_Material_#40015_0'].geometry} material={materials['Material_40.015']} />
          <mesh geometry={nodes.SPOT003_Standard_2014_0.geometry} material={materials['Standard_2.014']} />
        </group>
        <group position={[734.824, 1.084, 0]} rotation={[Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['SPOT004_Material_#39014_0'].geometry} material={materials['Material_39.014']} />
          <mesh geometry={nodes['SPOT004_Material_#40015_0'].geometry} material={materials['Material_40.015']} />
          <mesh geometry={nodes.SPOT004_Standard_2014_0.geometry} material={materials['Standard_2.014']} />
        </group>
        <group position={[1485.346, 1.084, 0]} rotation={[Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['SPOT006_Material_#39014_0'].geometry} material={materials['Material_39.014']} />
          <mesh geometry={nodes['SPOT006_Material_#40015_0'].geometry} material={materials['Material_40.015']} />
          <mesh geometry={nodes.SPOT006_Standard_2014_0.geometry} material={materials['Standard_2.014']} />
        </group>
        <group position={[1485.346, 1.084, 0]} rotation={[Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['SPOT007_Material_#39014_0'].geometry} material={materials['Material_39.014']} />
          <mesh geometry={nodes['SPOT007_Material_#40015_0'].geometry} material={materials['Material_40.015']} />
          <mesh geometry={nodes.SPOT007_Standard_2014_0.geometry} material={materials['Standard_2.014']} />
        </group>
        <group position={[0, 1.084, 0]} rotation={[Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['SPOT009_Material_#39014_0'].geometry} material={materials['Material_39.014']} />
          <mesh geometry={nodes['SPOT009_Material_#40015_0'].geometry} material={materials['Material_40.015']} />
          <mesh geometry={nodes.SPOT009_Standard_2014_0.geometry} material={materials['Standard_2.014']} />
        </group>
        <mesh geometry={nodes.Circle_Frozen_white_metal_0.geometry} material={materials.Frozen_white_metal} position={[0, 77.581, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Circle001_Material001_0.geometry} material={materials['Material.001']} position={[0, 77.581, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube_Old_Metal_0.geometry} material={materials.Old_Metal} position={[-127.702, 4.565, -43.131]} rotation={[-Math.PI / 2, 0, 0]} scale={4.499} />
        <mesh geometry={nodes.Plane001_Material002_0.geometry} material={materials['Material.002']} position={[3.627, 312.731, 143.563]} scale={[100, 58.335, 100]} />
      </group>
    </group>
  )
}

useGLTF.preload('/desk.glb')
